问题：
  File "/home/guohao/anaconda3/envs/env_fangzheng/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 930-931: invalid continuation byte
方法1：把'r'变成'rb'
